import { COLUMN_IDS, DEFAULT_AGE_BAND, getStageBehavior } from './constants.js';
import { nextColumnFor } from './congruence.js';

function rootView() { return { mode: 'buckets', bucketId: null, page: 1, history: [] }; }
export function makeRootColumnViews() { return Object.fromEntries(COLUMN_IDS.map((column) => [column, rootView()])); }
export function createInitialBoardState(stage = 1, ageBand = DEFAULT_AGE_BAND) { return { stage, ageBand, activeColumn: 1, sentence: [], pendingVerb: null, columnViews: makeRootColumnViews(), lastAnnouncement: 'Column 1 is active.' }; }
export function isColumnInteractive(state, column) { const behavior=getStageBehavior(state.stage); return behavior.interactionMode==='soft_guide'||state.activeColumn===column; }
function lastLanguageToken(sentence){ for(let i=sentence.length-1;i>=0;i-=1){ if((sentence[i]?.column??0)>=1)return sentence[i]; } return null; }
function thirdPersonVerb(text){ const [first,...rest]=text.split(' '); const lower=first.toLowerCase(); const irregular={have:'has',do:'does',go:'goes',"don't":"doesn't"}; let inflected; if(irregular[lower])inflected=irregular[lower]; else if(lower==="can't")inflected=first; else if(/[^aeiou]y$/i.test(first))inflected=`${first.slice(0,-1)}ies`; else if(/(s|sh|ch|x|z|o)$/i.test(first))inflected=`${first}es`; else inflected=`${first}s`; return [inflected,...rest].join(' '); }
function spokenText(state,word){ const base=word.spoken??word.label; if(state.stage!==1||state.ageBand!=='school_age'||word.column!==2)return base; const previous=lastLanguageToken(state.sentence); if(previous?.column===2)return base; const starter=state.sentence.find((token)=>token.column===1); return starter?.subjectAgreement==='third_person'?thirdPersonVerb(base):base; }
function appendToken(state,word,pending=false){ return [...state.sentence,{id:`${word.id}-${Date.now()}-${state.sentence.length}`,sourceId:word.id,text:spokenText(state,word),label:word.label,role:word.role,column:word.column,pending,...(word.subjectAgreement?{subjectAgreement:word.subjectAgreement}:{})}]; }
function restoreColumnView(views,column){ return {...views,[column]:rootView()}; }
function commitPendingVerbAsBase(state){ if(!state.pendingVerb)return state; return {...state,sentence:state.sentence.map((t)=>t.id===state.pendingVerb.tokenId?{...t,pending:false}:t),pendingVerb:null,columnViews:restoreColumnView(state.columnViews,3)}; }
function prepare(state,column){ return !state.pendingVerb||column===3?state:commitPendingVerbAsBase(state); }
function announce(label,next,stage){ const b=getStageBehavior(stage); return b.interactionMode==='soft_guide'?`${label} added. Column ${next} is suggested; every column remains available.`:`${label} added. Column ${next} is active.`; }
export function boardReducer(state,action){ switch(action.type){
case 'SET_STAGE': return createInitialBoardState(action.stage,state.ageBand);
case 'SET_AGE_BAND': return createInitialBoardState(state.stage,action.ageBand);
case 'OPEN_BUCKET': { if(!isColumnInteractive(state,action.column))return state; const s=prepare(state,action.column); const behavior=getStageBehavior(s.stage); return {...s,activeColumn:behavior.interactionMode==='soft_guide'?action.column:s.activeColumn,columnViews:{...s.columnViews,[action.column]:{mode:'words',bucketId:action.bucketId,page:action.page??1,history:[]}},lastAnnouncement:`${action.bucketLabel} opened in Column ${action.column}.`}; }
case 'OPEN_NESTED_BUCKET': { if(!isColumnInteractive(state,action.column))return state; const s=prepare(state,action.column); const current=s.columnViews[action.column]; if(current?.mode!=='words')return state; return {...s,columnViews:{...s.columnViews,[action.column]:{mode:'words',bucketId:action.bucketId,page:1,history:[...(current.history??[]),current.bucketId]}},lastAnnouncement:`${action.bucketLabel} opened.`}; }
case 'BACK': { if(!isColumnInteractive(state,action.column))return state; const s=prepare(state,action.column); const current=s.columnViews[action.column]; const history=current?.history??[]; if(current?.mode==='words'&&history.length){ const parent=history[history.length-1]; return {...s,columnViews:{...s.columnViews,[action.column]:{mode:'words',bucketId:parent,page:1,history:history.slice(0,-1)}},lastAnnouncement:'Previous bucket restored.'}; } const behavior=getStageBehavior(s.stage); return {...s,activeColumn:behavior.interactionMode==='soft_guide'?action.column:s.activeColumn,columnViews:restoreColumnView(s.columnViews,action.column),lastAnnouncement:`Column ${action.column} categories restored.`}; }
case 'SET_PAGE': if(!isColumnInteractive(state,action.column))return state; return {...state,columnViews:{...state.columnViews,[action.column]:{...state.columnViews[action.column],page:action.page}}};
case 'SELECT_WORD': { if(!isColumnInteractive(state,action.column)||action.word.targetBucketId)return state; const s=prepare(state,action.column),word=action.word,b=getStageBehavior(s.stage); if(word.column===2&&word.grammarProfileId&&b.useVerbGrammarOverlay){ const sentence=appendToken(s,word,true); return {...s,sentence,pendingVerb:{tokenId:sentence.at(-1).id,sourceWord:word,grammarProfileId:word.grammarProfileId},activeColumn:3,columnViews:{...restoreColumnView(s.columnViews,2),3:{mode:'grammar',grammarProfileId:word.grammarProfileId,bucketId:null,page:1,history:[]}},lastAnnouncement:`${word.label} selected. Choose its grammar form in Column 3.`}; } const sentence=appendToken(s,word,false); if(word.slamShutTrigger&&b.slamShutAfterTarget)return {...createInitialBoardState(s.stage,s.ageBand),sentence,lastAnnouncement:`${word.label} added. Board reset to Column 1.`}; const next=word.nextColumnOverride??nextColumnFor(word.column,s.stage); return {...s,sentence,activeColumn:next,columnViews:next===word.column?s.columnViews:restoreColumnView(s.columnViews,word.column),lastAnnouncement:announce(word.label,next,s.stage)}; }
case 'SELECT_GRAMMAR': { if(!state.pendingVerb||state.columnViews[3]?.mode!=='grammar')return state; const v=action.variant; const sentence=state.sentence.map((t)=>t.id===state.pendingVerb.tokenId?{...t,text:v.spoken??v.label,label:v.label,pending:false,grammarForm:v.form}:t); const next=nextColumnFor(3,state.stage); return {...state,sentence,pendingVerb:null,activeColumn:next,columnViews:restoreColumnView(state.columnViews,3),lastAnnouncement:announce(v.label,next,state.stage)}; }
case 'INTERRUPT': { if(action.interrupt.action==='clear')return createInitialBoardState(state.stage,state.ageBand); const token={id:`interrupt-${action.interrupt.id}-${Date.now()}`,sourceId:action.interrupt.id,text:action.interrupt.spoken,label:action.interrupt.label,role:'interrupt',column:0,pending:false}; return {...state,sentence:[...state.sentence,token],lastAnnouncement:`${action.interrupt.label} added.`}; }
case 'UNDO': { if(!state.sentence.length)return state; const removed=state.sentence.at(-1),wasPending=removed.id===state.pendingVerb?.tokenId; return {...state,sentence:state.sentence.slice(0,-1),pendingVerb:wasPending?null:state.pendingVerb,activeColumn:wasPending?2:state.activeColumn,columnViews:wasPending?{...restoreColumnView(state.columnViews,2),3:rootView()}:state.columnViews,lastAnnouncement:`${removed.label} removed.`}; }
case 'RESET_BOARD': return {...createInitialBoardState(state.stage,state.ageBand),sentence:state.sentence};
default:return state; }}
